#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  potentiometer,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  bumpSwitch,     sensorTouch)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           ballDump,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           dispenser,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           trayMotor,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
RobotC program for a marble sorting machine.

Procedure:
- Check weight to sort out the steel marbles
- Check the opacity of the object by calling the ``checkMarble`` function
- Release a new marble

Author: Kamran Hussain
*/

int startStatus = 0;

void switchBins(int bin) {	// Function that switches the sorting bins
	if(bin==1){
		setServo(trayMotor, 0);
	} else if (bin==2) {
		setServo(trayMotor, 127);
	}
}

task checkStart() {	// Function that checks if the start button has been pressed
	if(SensorValue(bumpSwitch) == 1) {
		startStatus = 1;
	} else {
		startStatus = 0;
	}
}

void dump() {	// Function that releases/dumps a new marble
	setServo(dispenser, -127);
	wait(1);
	setServo(dispenser, 127);
}

void checkOpacity() { // Sorting function that uses sensors to determine material based on opacity
	if(SensorValue(lightSensor) < 20) {
		switchBins(1); // This signifies the clear marble
	}
	switchBins(0); // This signifies the wooden marble
}

task main() // Main function with all procedural code
{
	startTask(checkStart);

	while(1==1) {
		while(startStatus == 1) {
			turnFlashlightOn(flashlight, 127); // Turn on the flashlight to illuminate the second sorting area
			dump();	// Dump a new ball
			checkOpacity();	// Check the opacity if the ball is not steel
			wait(5); 		// Wait for 5 seconds for the sorting to take place
		}
		turnFlashlightOff(flashlight);
	}

}
