#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  bumpSwitch,     sensorTouch)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           ballDump,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           dispenser,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           trayMotor,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
RobotC program for a marble sorting machine.

Procedure:
- Check weight to sort out the steel marbles
- Check the opacity of the object by calling the ``checkMarble`` function
- Release a new marble

Author: Kamran Hussain
*/

void switchBins(int bin) {	// Function that switches the sorting bins
	if(bin==1){
		setServo(trayMotor, -127);
	} else if (bin==2) {
		setServo(trayMotor, 127);
	}
}

int startStatus = 0; // default value of zero to signify the start button hasnt been pressed.
task checkStart() {	// Function that checks if the start button has been pressed
	while(1==1) {
		if(SensorValue(bumpSwitch) == 1) {
			startStatus = 1;
		}
	}
}

void dump() {	// Function that releases/dumps a new marble
	startMotor(dispenser, -12);
	//wait(0.5);
	//stopMotor(dispenser);
}

void checkOpacity() { // Sorting function that uses sensors to determine material based on opacity
	if(SensorValue(lightSensor) < 120) {
		switchBins(1); // This signifies the clear marble
		setServo(ballDump, 127);
		wait(1);
		setServo(ballDump, -127);
	} else if(SensorValue(lightSensor) > 200) {
		switchBins(0); // This signifies the wooden marble
		setServo(ballDump, 127);
		wait(1);
		setServo(ballDump, -127);
	}
}

task main() // Main function with all procedural code
{
	startTask(checkStart);
	turnFlashlightOn(flashlight);
	setServo(ballDump, -127);
	while(1==1) {
		while(startStatus == 1) {
			turnFlashlightOn(flashlight); // Turn on the flashlight to illuminate the second sorting area
			dump();	// Dump a new ball
			checkOpacity();	// Check the opacity if the ball is not steel
			wait(5); 		// Wait for 5 seconds for the sorting to take place
		}
		turnFlashlightOff(flashlight);
	}

}
